# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'unknown'), (1, 'Action'), (2, 'Adventure'), (3, 'Animation'), (4, 'Childrens'), (5, 'Comedy'), (6, 'Crime'), (7, 'Documentary'), (8, 'Drama'), (9, 'Fantasy'), (10, 'Film_Noir'), (11, 'Horror'), (12, 'Musical'), (13, 'Mystery'), (14, 'Romance'), (15, 'Sci_Fi'), (16, 'Thriller'), (17, 'War'), (18, 'Western')], max_length=46)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
